# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: students_details.proto for package 'students_details'

require 'grpc'
require_relative 'students_details_pb'

module StudentsDetails
  module StudentsDetailsService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'students_details.StudentsDetailsService'

      rpc :Hello, HelloRequest, HelloResponse
      rpc :SearchStudents, SearchRequest, Students
    end

    Stub = Service.rpc_stub_class
  end
end
